import time
from selenium.webdriver import ActionChains
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import re
from selenium.webdriver.common.keys import Keys
import os
from dotenv import load_dotenv

def test_textbox_interaction():
    load_dotenv('.env')
    mail = os.getenv("MAIL")
    password = os.getenv("PASSWORD")
    senwas125 = os.getenv('SENWAS125')
    proyecto_postpago = os.getenv('PROTECTO_POSTPAGO')
    alcatel_3078a_black = os.getenv('PRODUCT_TO_SEARCH')
    consignacion_multiplan = os.getenv('CONSIGNACION_MULTIPLAN_SIF')
    limite_de_pago = os.getenv('LIMITE_DE_CREDIT')
    driver = webdriver.Chrome()
    equipo_fijo = os.getenv('EQUIPO_FIJOS')
    driver.get('https://tiendadacqa.claro.com.do/clarodac/cart/')
    # time.sleep(120)

    input_element = driver.find_elements(By.CLASS_NAME, 'input')
    input_element[0].send_keys(mail)
    input_element[1].send_keys(password)
    button_element = driver.find_element(By.CLASS_NAME, 'button')
    driver.execute_script("arguments[0].click();", button_element)
    time.sleep(3)
    driver.get('https://tiendadacqa.claro.com.do/clarodac/partner-profile')
    time.sleep(3)
    element = driver.find_element(By.XPATH, '//*[@id="app"]/div/div/div[2]/div/div/div/div/div[1]/div[2]/div/p')
    print(element.text)
    text = re.sub(r'[^\d.]+', '', element.text)
    NumeroEnteroGG = float(text)
    print('Credito disponible :',NumeroEnteroGG)
    time.sleep(3)
    Buscar = driver.find_element(By.CLASS_NAME, 'input')
    Buscar.send_keys(alcatel_3078a_black, Keys.ENTER)
    time.sleep(3)
    button_GG = driver.find_element(By.XPATH, '//*[@id="app"]/div/div/div[2]/section/div/section[2]/section[1]/div/div[6]/button[2]')
    driver.execute_script("arguments[0].click();", button_GG)
    time.sleep(3)
    Selec_tip_orden =driver.find_element(By.XPATH, '/html/body/div[1]/section/section/div/div/div[2]/div/div[2]/div/div[1]/div[2]/div[2]/div/div[1]/button/span')
    driver.execute_script("arguments[0].click();", Selec_tip_orden)
    time.sleep(3)
    proyecto_postpago = driver.find_element(By.XPATH, proyecto_postpago)
    driver.execute_script("arguments[0].click();", proyecto_postpago)
    time.sleep(4)
    Seleccionar = driver.find_element(By.XPATH, '/html/body/div[1]/section/section/div/div/div[2]/div/div[2]/div/div[1]/div[2]/div[2]/div/div[1]/div[2]/div[2]/div/footer/button[1]/span')
    driver.execute_script("arguments[0].click();", Seleccionar)
    time.sleep(4)
    Increment = driver.find_element(By.XPATH, '//*[@id="app"]/div/div/div[2]/div/div[2]/div/div[2]/div[1]/div/table/tbody/tr[8]/td[3]/div/div/p[2]/button')
    driver.execute_script("arguments[0].click();", Increment)
    time.sleep(4)
    Añadir_Carrito = driver.find_element(By.XPATH, '/html/body/div[1]/section/section/div/div/div[2]/div/div[2]/div/div[2]/div[1]/div/table/tbody/tr[8]/td[4]/section/button')
    driver.execute_script("arguments[0].click();", Añadir_Carrito)
    time.sleep(2)
    ButtonCerrar = driver.find_element(By.XPATH, '//*[@id="app"]/div/div/div[2]/div/div[2]/div/button')
    driver.execute_script("arguments[0].click();", ButtonCerrar)
    time.sleep(3)
    ButtonCarrito = driver.find_element(By.XPATH, '//*[@id="app"]/div/div/div[1]/nav/div[2]/div[2]/div/div/button[1]')
    driver.execute_script("arguments[0].click();", ButtonCarrito)
    time.sleep(3)
    ProcesarOrder = driver.find_element(By.XPATH, '/html/body/div[1]/section/section/div/div/div[2]/div/div[2]/div/section/div[1]/div/div[3]/div[2]/div/div[7]/button')
    driver.execute_script("arguments[0].click();", ProcesarOrder)
    time.sleep(3),
    ButtonLimiteCredito = driver.find_element(By.XPATH, "//*[contains(text(), 'Limite de Credito')]")
    driver.execute_script("arguments[0].click();", ButtonLimiteCredito)
    time.sleep(3)
    TotalOrden = driver.find_element(By.XPATH,'/html/body/div[1]/section/section/div/div/div[2]/div/div[2]/div/section/div[2]/div/div[1]/div/section/section/section/section/div/div[1]/div/div[2]/p/span')
    text2 = re.sub(r'[^\d.]+', '', TotalOrden.text)
    NumeroEntero = float(text2)
    print('Total de la orden: ', NumeroEntero)
    ResumenOrden = driver.find_element(By.XPATH, '/html/body/div[1]/section/section/div/div/div[2]/div/div[2]/div/section/div[2]/div/div[2]/div/div[7]/button/span')
    driver.execute_script("arguments[0].click();", ResumenOrden)
    time.sleep(10)
    Resta = NumeroEnteroGG - NumeroEntero
    Resta2 = round(Resta, 5)
    print('Valor de la resta : ',Resta2)
    driver.get('https://tiendadacqa.claro.com.do/clarodac/partner-profile')
    time.sleep(3)
    MontoActuar = driver.find_element(By.XPATH, '//*[@id="app"]/div/div/div[2]/div/div/div/div/div[1]/div[2]/div/p')
    time.sleep(3)
    text3 = re.sub(r'[^\d.]+', '', MontoActuar.text)
    NumeroEntero3 = float(text3)
    print('Monto actual',NumeroEntero3)
    if NumeroEntero3 == Resta2:
        print('El monto es igual')
    else:
        print('Los montos son diferentes')
    MisPedidos = driver.find_element(By.XPATH, '//*[@id="app"]/div/div/div[1]/div[1]/div[1]/a[2]')
    driver.execute_script("arguments[0].click();", MisPedidos)
    time.sleep(2)
    IdOrden = driver.find_element(By.XPATH, '//*[@id="app"]/div/div/div[2]/main/div[2]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div[2]/h1[1]/span')
    print(IdOrden.text)
    time.sleep(2)
    # # driver.get('https://tiendadacqa.claro.com.do/adminclarodac/Admin')
    # # time.sleep(2)
    # # Ordenes = driver.find_element(By.XPATH, '//*[@id="nopcommerce-common-statistics-box"]/div[2]/div[1]/div/a')
    # # time.sleep(10)
    # # driver.execute_script("arguments[0].click();", Ordenes)


